### ISSUE TITLE
Wrong version on npm install

### ISSUE THREAD

**Issue by yeelan0319** [joe1chen/nodebb-plugin-sso-linkedin-oauth2#1]
Hi Joe1chen,

It seems the npm didn't get your latest update for this module. So when I do `npm install nodebb-plugin-sso-linkedin-oauth2`, it still gives me `version 0.2.2` instead of `version 0.3.0`. This is little bit confusing to find out why the plugin doesn't work on nodebb 0.6.0 especially when I see your commit specified update to 0.6.0. Also it makes me manual install the latest version when I try to deploy to another machine.

I really appreciate if you can do a `npm publish` to update the version on npm. Thanks!

**Comment by joe1chen** [comment]
Sorry about this.. it's fixed now.
